-- AlterTable
ALTER TABLE "Ingredient"
ADD COLUMN IF NOT EXISTS "pricePerUnit" DOUBLE PRECISION DEFAULT 0,
ADD COLUMN IF NOT EXISTS "priceCurrency" TEXT DEFAULT 'VND',
ADD COLUMN IF NOT EXISTS "priceUpdatedAt" TIMESTAMP(3);

